package com.food.ordering.zinger.constant;

public class Sql {
    public static final String SELECT = " SELECT ";
    public static final String UPDATE = " UPDATE ";
    public static final String WHERE = " WHERE ";
    public static final String AND = " AND ";
    public static final String ON = " ON ";
    public static final String FROM = " FROM ";
    public static final String LIKE = " LIKE ";
    public static final String LIMIT = " LIMIT ";
    public static final String OFFSET = " OFFSET ";
    public static final String COLON = ":";
    public static final String COMMA_COLON = ", :";
    public static final String EQUAL_COLON = " = :";
    public static final String EQUALS = " = ";
    public static final String NOT_EQUALS = " != ";
    public static final String LESS_THAN = " < ";
    public static final String PERCENT = "%";
    public static final String LEFT_PARANTHESIS = "(";
    public static final String RIGHT_PARANTHESIS = ")";
    public static final String COMMA = ", ";
    public static final String UNION = " UNION ";
    public static final String SINGLE_QUOTE = "'";
    public static final String IN = " IN ";
    public static final String AS = " AS ";
    public static final String DOT = ".";
    public static final String ORDER_BY = " ORDER BY ";
    public static final String ASC = " ASC";
    public static final String DESC = " DESC";
    public static final String SET = " SET ";
    public static final String INSERT_INTO = "INSERT INTO ";
    public static final String DELETE_FROM = "DELETE FROM ";
    public static final String CONCATENATION_OPERATOR = " || ";
    public static final String VALUES = " VALUES";
    public static final String INNER_JOIN = " INNER JOIN ";
    public static final String CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP";
    public static final String TIMESTAMPDIFF = "TIMESTAMPDIFF";
    public static final String MINUTE = "MINUTE";
}
