package com.food.ordering.zinger.constant;

public class Sql {
    public static final String SELECT = " SELECT ";
    public static final String UPDATE = " UPDATE ";
    public static final String WHERE = " WHERE ";
    public static final String AND = " AND ";
    public static final String OR = " OR ";
    public static final String ON = " ON ";
    public static final String DATE = " DATE ";
    public static final String FROM = " FROM ";
    public static final String LIKE = " LIKE ";
    public static final String ELSE = " ELSE ";
    public static final String LIMIT = " LIMIT ";
    public static final String OFFSET = " OFFSET ";
    public static final String COLON = ":";
    public static final String COMMA_COLON = ", :";
    public static final String EQUAL_COLON = " = :";
    public static final String EMPTY_QUOTES = "''";
    public static final String EQUALS = " = ";
    public static final String NOT_EQUALS = "!=";
    public static final String DOT = ".";
    public static final String LEFT_PARANTHESIS = "(";
    public static final String RIGHT_PARANTHESIS = ")";
    public static final String COMMA = ", ";
    public static final String SINGLE_QUOTE = "'";
    public static final String SINGLE_QT_COMMA_SINGLE_QT = "','";
    public static final String TO_DATE = " TO_DATE(";
    public static final String GREATER = ">";
    public static final String GREATER_THAN_EQUAL_TO = ">=";
    public static final String LESSER_THAN_EQUAL_TO = "<=";
    public static final String LESSER = "<";
    public static final String NOT_IN = " NOT IN ";
    public static final String IN = " IN ";
    public static final String IS = " IS ";
    public static final String NULL = " NULL ";
    public static final String NOT = " NOT ";
    public static final String ORDER_BY = " ORDER BY ";
    public static final String IS_NOT_NULL = IS + NOT + NULL;
    public static final String IS_NULL = IS + NULL;
    public static final String STAR = "*";
    public static final String DELETE = "DELETE";
    public static final String NULLIF = " NULLIF(";
    public static final String DIVIDED_BY = " / ";
    public static final String ASC = " ASC";
    public static final String DESC = " DESC";
    public static final String SET = " SET ";
    public static final String BETWEEN = " BETWEEN ";
    public static final String DISTINCT = " DISTINCT ";
    public static final String COALESCE = " COALESCE( ";
    public static final String SUM = " SUM (";
    public static final String INNER_JOIN = " INNER JOIN ";
    public static final String JOIN = " JOIN ";
    public static final String CAST = " CAST ";
    public static final String SYSTIMESTAMP = "SYSTIMESTAMP";
    public static final String SYSDATE = "SYSDATE";
    public static final String COUNT = " COUNT ";
    public static final String COUNT_STAR = " COUNT (*) ";
    public static final String INSERT_INTO = "INSERT INTO ";
    public static final String DELETE_FROM = "DELETE FROM ";
    public static final String SELECT_STAR_FROM = "SELECT * FROM ";
    public static final String SELECT_COUNT_STAR_FROM = "SELECT COUNT(*) FROM ";
    public static final String TIME_FORMAT = "yyyy-mm-dd hh24:mi:ss";
    public static final String DATE_FORMAT = "YYYY-MM-DD";
    public static final String GROUPBY = " group by ";
    public static final String CONCATENATION_OPERATOR = " || ";
    public static final String CONCAT = "CONCAT";
    public static final String SPACE_STRING = " ' ' ";
    public static final String AS = " AS ";
    public static final String EMPTY_SPACE = " ";
    public static final String VALUES = " VALUES";
    public static final String CURRENT_TIMESTAMP = "CURRENT_TIMESTAMP";
}

